---
- name: Amazon Linuxの場合、python 2.7をデフォルトとして設定
  alternatives:
    name: python
    link: /usr/bin/python
    path: /usr/bin/python2.7
  when: ansible_distribution == "Amazon"

- name: selinux関連モジュールをインストール
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - selinux-policy-targeted
    - policycoreutils-python
    - libselinux-python

- name: EPELリポジトリを登録
  copy: src=epel.repo dest=/etc/yum.repos.d/epel.repo

- name: EPEL用のGPGキーを設置
  copy: src=RPM-GPG-KEY-EPEL-6 dest=/etc/pki/rpm-gpg

- name: SELinuxをpermissiveモードに設定
  selinux: policy=targeted state=permissive
