---
- name: mackerelリポジトリを追加
  shell: curl -fsSL {{ mackerel_setup_yum_url }} | sh

- name: mackerel-agentをインストール
  yum:
    name: mackerel-agent

- name: mackerel-agent.confにapikeyを追記
  lineinfile:
    dest: /etc/mackerel-agent/mackerel-agent.conf
    line: "apikey = \"{{ mackerel_api_key }}\""
    regexp: "^apikey\\s*="

- name: mackerel-agentを起動
  service:
    name: mackerel-agent
    state: started
    enabled: yes
