---
- name: Uninstall Wordpress, MySQL, Nginx, and PHP-FPM
  hosts: wordpress-server
  sudo: yes
  tasks:
    - name: php-fpm, nginx, mysqlのプロセスを停止
      service: name={{ item }} state=stopped
      with_items:
        - php-fpm
        - nginx
        - mysqld

    - name: 設置済みファイルを削除
      file: path={{ item }} state=absent
      with_items:
        - /srv/wordpress
        - /etc/php-fpm.d
        - /etc/nginx
        - /etc/my.cnf
        - /var/lib/mysql

    - name: mysql-serverをアンインストール
      yum: name=mysql-server state=absent

    - name: モジュールをアンインストール
      yum: name={{ item }} state=absent
      with_items:
        - MySQL-python
        - nginx
        - php
        - php-fpm
        - php-enchant
        - php-IDNA_Convert
        - php-mbstring
        - php-mysql
        - php-PHPMailer
        - php-process
        - php-simplepie
        - php-xml
