---
- hosts: localhost
  roles:
    - role: idcf_vm
      idcf_vm_name: wordpress-server
      idcf_vm_ssh_key_name: ansible-handson
      idcf_vm_ports:
        - port: 80
          protocol: tcp

- include: site.yml
