---
- hosts: localhost
  connection: local
  tasks:
    - name: SSH公開鍵を送信
      cs_sshkeypair:
        name: "{{ cs_ssh_key_name }}"
        public_key: "{{ cs_ssh_public_key }}"
        api_url: "{{ cs_api_url }}"
        api_key: "{{ cs_api_key }}"
        api_secret: "{{ cs_secret_key }}"

    - name: VMを作成
      cs_virtualmachine:
        name: "{{ cs_vm_name }}"
        hypervisor: VMware
        service_offering: "{{ cs_vm_spec }}"
        template: ec45fa26-e5d0-45a7-b57d-0c3f8e36ff3b
        ssh_key: "{{ cs_ssh_key_name }}"
        api_url: "{{ cs_api_url }}"
        api_key: "{{ cs_api_key }}"
        api_secret: "{{ cs_secret_key }}"

    - name: FirewallでSSHとHTTPを開放
      cs_firewall:
        ip_address: "{{ cs_public_ip }}"
        start_port: "{{ item }}"
        end_port: "{{ item }}"
        cidr: 0.0.0.0/0
        api_url: "{{ cs_api_url }}"
        api_key: "{{ cs_api_key }}"
        api_secret: "{{ cs_secret_key }}"
      with_items:
        - 22
        - 80

    - name: 作成されたVMへのSSHとHTTPのポートフォワーディングを設定
      cs_portforwarding:
        ip_address: "{{ cs_public_ip }}"
        vm: "{{ cs_vm_name }}"
        public_port: "{{ item }}"
        private_port: "{{ item }}"
        api_url: "{{ cs_api_url }}"
        api_key: "{{ cs_api_key }}"
        api_secret: "{{ cs_secret_key }}"
      with_items:
        - 22
        - 80

    - name: SSHポートに接続できることを確認
      wait_for:
        host: "{{ cs_public_ip }}"
        port: 22
        state: started

    - name: SSH秘密鍵ファイルを配置
      copy:
        dest: "/tmp/{{ cs_public_ip }}.pem"
        content: "{{ cs_ssh_private_key }}"
        mode: 0400

    - name: 作成されたVMをホストに追加
      add_host:
        name: "{{ cs_public_ip }}:22"
        groups: wordpress-server
        ansible_ssh_user: root
        ansible_ssh_private_key_file: "/tmp/{{ cs_public_ip }}.pem"
        mackerel_api_key: "{{ mackerel_api_key }}"

- include: site.yml
