---
- name: Wordpress, MySQL, Nginx, PHP-FPMをインストール
  hosts: wordpress-server
  sudo: yes

  roles:
    - common
    - mysql
    - nginx
    - php-fpm
    - wordpress
    - role: mackerel
      when: mackerel_api_key is defined and mackerel_api_key
