---
- name: SSH鍵を作成
  command: ssh-keygen -f ~/.ssh/id_rsa-{{ idcf_vm_ssh_key_name }} -N ""
  args:
    creates: ~/.ssh/id_rsa-{{ idcf_vm_ssh_key_name }}

- name: SSH鍵をアップロード
  cs_sshkeypair:
    name: "{{ idcf_vm_ssh_key_name }}"
    public_key: "{{ lookup('file', '~/.ssh/id_rsa-{}.pub'.format(idcf_vm_ssh_key_name)) }}"

- name: VMインスタンスを作成
  cs_instance:
    name: "{{ idcf_vm_full_name }}"
    hypervisor: VMware
    template: "{{ idcf_vm_template }}"
    service_offering: "{{ idcf_vm_spec }}"
    ssh_key: "{{ idcf_vm_ssh_key_name }}"
    poll_async: no
  register: idcf_vm_status

- name: スタティックナット設定をインクルード
  include: set_staticnat.yml
  when: not idcf_vm_status.get('public_ip')

- name: パブリックIP用変数をセット
  set_fact:
    idcf_vm_public_ip: "{{ idcf_vm_status.get('public_ip') or idcf_vm_registered_public_ip }}"

- name: pingを許可
  cs_firewall:
    ip_address: "{{ idcf_vm_public_ip }}"
    protocol: icmp
    icmp_type: 8
    icmp_code: 0

- name: ポートを解放
  cs_firewall:
    ip_address: "{{ idcf_vm_public_ip }}"
    port: "{{ item.get('port', 0) }}"
    protocol: "{{ item.get('protocol', 'tcp') }}"
    cidr: "{{ item.get('cidr', '0.0.0.0/0') }}"
  with_flattened:
    - port: 22
    - "{{ idcf_vm_ports }}"

- name: VMインスタンス作成完了を待機
  cs_instance:
    name: "{{ idcf_vm_full_name }}"
  register: idcf_vm_status

- name: VMへのSSH接続を確認
  wait_for:
    host: "{{ idcf_vm_status.public_ip }}"
    port: 22

- name: Ansibleのデプロイ対象にVMを追加
  add_host:
    name: "{{ idcf_vm_full_name }}"
    ansible_host: "{{ idcf_vm_status.public_ip }}"
    groups: "{{ ','.join(idcf_vm_inventory_groups) }}"
    ansible_user: "{{ idcf_vm_ssh_user }}"
    ansible_ssh_private_key_file: "~/.ssh/id_rsa-{{ idcf_vm_ssh_key_name }}"
