---
- name: VMインスタンスを作成
  cs_instance:
    name: "{{ idcf_vm_full_name }}"
    hypervisor: VMware
    template: "{{ idcf_vm_template }}"
    service_offering: "{{ idcf_vm_spec }}"
    ssh_key: "{{ idcf_vm_ssh_key_name }}"
    poll_async: no
  register: idcf_vm_status

- name: パブリックIPアドレスを発行
  cs_ip_address:
  register: idcf_vm_public_ip
  when: idcf_vm_public_ip is not defined and not idcf_vm_status.get('public_ip')

- name: スタティックナットを設定
  cs_staticnat:
    ip_address: "{{ idcf_vm_public_ip.ip_address }}"
    vm: "{{ idcf_vm_full_name }}"
  when: not idcf_vm_status.get('public_ip')

- name: pingを許可
  cs_firewall:
    ip_address: "{{ idcf_vm_status.get('public_ip') or idcf_vm_public_ip.ip_address }}"
    protocol: icmp
    icmp_type: 8
    icmp_code: 0

- name: ポートを解放
  cs_firewall:
    ip_address: "{{ idcf_vm_status.get('public_ip') or idcf_vm_public_ip.ip_address }}"
    port: "{{ item.get('port', 0) }}"
    protocol: "{{ item.get('protocol', 'tcp') }}"
    cidr: "{{ item.get('cidr', '0.0.0.0/0') }}"
  with_flattened:
    - port: 22
    - "{{ idcf_vm_ports }}"

- name: VMインスタンス作成完了を待機
  cs_instance:
    name: "{{ idcf_vm_full_name }}"
  register: idcf_vm_status

- name: VMへのSSH接続を確認
  wait_for:
    host: "{{ idcf_vm_status.public_ip }}"
    port: 22

- name: Ansibleのデプロイ対象にVMを追加
  add_host:
    name: "{{ idcf_vm_full_name }}"
    ansible_ssh_host: "{{ idcf_vm_status.public_ip }}"
    groups: "{{ ','.join(idcf_vm_inventory_groups) }}"
    ansible_ssh_user: "{{ idcf_vm_ssh_user }}"
